name: Deploy TEST 

on:
  push:
    branches:
      - test
    paths-ignore: 
      - README.md
      - LICENSE
jobs:
  deploy:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - name: Deploy to Server   
        uses: YangsCalvin/rsync-deploy@v1.0
        env:
          DEPLOY_KEY: ${{ secrets.TEST_SERVER_KEY }}   
          ARGS: -avz --delete --exclude='*.env' --exclude='runtime/'
          SERVER_PORT: ${{ secrets.TEST_SERVER_PORT }}
          FOLDER: ./ 
          SERVER_IP: ${{ secrets.TEST_SERVER_HOST }}    
          USERNAME: ${{ secrets.TEST_SERVER_USERNAME }} 
          SERVER_DESTINATION: /home/test
